# Generated by Django 3.0.8 on 2020-10-14 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='desc',
        ),
    ]
