# Generated by Django 3.0.8 on 2020-10-16 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_remove_profile_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='describeyourself',
            field=models.CharField(default='describe yourself in less than 200 words', max_length=200),
            preserve_default=False,
        ),
    ]
