# Generated by Django 3.0.8 on 2020-10-16 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_profile_describeyourself'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='describeyourself',
        ),
    ]
